services:
    BobHearnIT\StripeIntegrationBundle\Client\StripeClient:
        autoconfigure: true
        autowire: false
        arguments:
            $stripePrivateKey: '%bobhearnit.stripe_integration.key%'

    BobHearnIT\StripeIntegrationBundle\Client\StripeClientInterface: '@BobHearnIT\StripeIntegrationBundle\Client\StripeClient'

    BobHearnIT\StripeIntegrationBundle\Services\StripeService:
        autoconfigure: true
        autowire: false
        arguments:
            $client: '@BobHearnIT\StripeIntegrationBundle\Client\StripeClientInterface'
            $translator: '@translator'

    BobHearnIT\StripeIntegrationBundle\Services\StripeServiceInterface: '@BobHearnIT\StripeIntegrationBundle\Services\StripeService'